"""
train_model.py
---------------
Trains a neural network (MLP) on MFCC features to classify speech emotion.

By default this runs on a synthetic demo dataset (data/emotion_features_demo.csv)
generated by generate_demo_data.py, so the whole pipeline works out of the
box with zero downloads. Once you've run feature_extraction.py against a
real dataset (RAVDESS/TESS/EMO-DB), point --data_path at the resulting CSV
to train on real speech:

    python src/train_model.py --data_path data/emotion_features.csv
"""

import argparse
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report

import tensorflow as tf
from tensorflow.keras import layers, models

from generate_demo_data import generate_demo_dataset

RANDOM_SEED = 42
OUTPUTS_DIR = "outputs"
MODELS_DIR = "models"
DEMO_DATA_PATH = "data/emotion_features_demo.csv"


def load_data(data_path: str) -> pd.DataFrame:
    if data_path == DEMO_DATA_PATH and not os.path.exists(data_path):
        print("No demo dataset found — generating synthetic MFCC data...")
        df = generate_demo_dataset()
        os.makedirs("data", exist_ok=True)
        df.to_csv(data_path, index=False)
    else:
        df = pd.read_csv(data_path)
    return df


def build_mlp(input_dim: int, num_classes: int):
    model = models.Sequential(
        [
            layers.Input(shape=(input_dim,)),
            layers.Dense(256, activation="relu"),
            layers.BatchNormalization(),
            layers.Dropout(0.3),
            layers.Dense(128, activation="relu"),
            layers.BatchNormalization(),
            layers.Dropout(0.3),
            layers.Dense(64, activation="relu"),
            layers.Dense(num_classes, activation="softmax"),
        ]
    )
    model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
    return model


def main(data_path: str):
    os.makedirs(OUTPUTS_DIR, exist_ok=True)
    os.makedirs(MODELS_DIR, exist_ok=True)
    tf.random.set_seed(RANDOM_SEED)

    df = load_data(data_path)
    X = df.drop(columns=["emotion"]).values
    y_raw = df["emotion"].values

    label_encoder = LabelEncoder()
    y = label_encoder.fit_transform(y_raw)
    joblib.dump(label_encoder, f"{MODELS_DIR}/label_encoder.joblib")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=RANDOM_SEED, stratify=y
    )
    X_train, X_val, y_train, y_val = train_test_split(
        X_train, y_train, test_size=0.15, random_state=RANDOM_SEED, stratify=y_train
    )

    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_val = scaler.transform(X_val)
    X_test = scaler.transform(X_test)
    joblib.dump(scaler, f"{MODELS_DIR}/scaler.joblib")

    model = build_mlp(X_train.shape[1], len(label_encoder.classes_))
    model.summary()

    early_stop = tf.keras.callbacks.EarlyStopping(
        monitor="val_loss", patience=15, restore_best_weights=True
    )

    history = model.fit(
        X_train,
        y_train,
        validation_data=(X_val, y_val),
        epochs=100,
        batch_size=32,
        callbacks=[early_stop],
        verbose=2,
    )

    test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
    print(f"\nTest accuracy: {test_acc:.4f}")
    print(f"Test loss: {test_loss:.4f}")

    y_pred = np.argmax(model.predict(X_test), axis=1)
    print("\n" + classification_report(y_test, y_pred, target_names=label_encoder.classes_))

    # Training curves
    fig, axes = plt.subplots(1, 2, figsize=(11, 4))
    axes[0].plot(history.history["accuracy"], label="train")
    axes[0].plot(history.history["val_accuracy"], label="val")
    axes[0].set_title("Accuracy")
    axes[0].set_xlabel("Epoch")
    axes[0].legend()

    axes[1].plot(history.history["loss"], label="train")
    axes[1].plot(history.history["val_loss"], label="val")
    axes[1].set_title("Loss")
    axes[1].set_xlabel("Epoch")
    axes[1].legend()
    plt.tight_layout()
    plt.savefig(f"{OUTPUTS_DIR}/training_curves.png", dpi=150)
    plt.close()

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(7, 6))
    sns.heatmap(
        cm, annot=True, fmt="d", cmap="Blues",
        xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_,
    )
    plt.title(f"Confusion Matrix (Test Accuracy = {test_acc:.3f})")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.savefig(f"{OUTPUTS_DIR}/confusion_matrix.png", dpi=150)
    plt.close()

    model.save(f"{MODELS_DIR}/emotion_mlp_model.keras")
    print(f"\nModel saved to {MODELS_DIR}/emotion_mlp_model.keras")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--data_path", default=DEMO_DATA_PATH)
    args = parser.parse_args()
    main(args.data_path)
